# Exclude the following directories:
exclude = [
    ".git",
    ".git-rewrite",
    ".ipynb_checkpoints",
    ".pyenv",
    ".ruff_cache",
    ".vscode",
    "__pycache__",
    "__pypackages__",
    "src/__pycache__",
    "src/pages/__pycache__",
    "data/R",
]

line-length = 90

# Automatically apply 'safe' fixes:
fix = true

# Enumerate all fixed violations:
show-fixes = true

# Assume Python >= 3.11
target-version = "py311"

[lint]
select = [
    "A",    # flake8-builtins
    "B",    # flake8-bugbear
    "C4",   # flake8-comprehensions
    "COM",  # flake8-commas
    "E",    # pycodestyle-error
    "ERA",  # flake8-eradicate
    "EXE",  # flake8-executable
    "F",    # pyflakes
    "FBT",  # flake8-boolean-trap
    "FLY",  # pyflint
    "FURB", # refurb
    "I",    # isort
    "ICN",  # flake8-import-conventions
    "ISC",  # flake8-implicit-str-concat
    "N",    # pep8-naming
    "PERF", # perflint
    "PIE",  # flake8-pie
    "PL",   # pylint
    "Q",    # flake8-quotes
    "RET",  # flake8-return
    "RSE",  # flake8-raise
    "RUF",  # ruff
    "S",    # flake8-bandit
    "SIM",  # flake8-simpify
    "UP",   # pyupgrade
    "W",    # pycodestyle-warning
    "YTT",  # flake8-2020
]

ignore = [
    "FBT002",  # don't report boolean default function arguments
    "PLR2004", # don't report magic numbers
    "RET504",  # don't report unnecessary variable assignment before return
    "SIM108",  # don't prefer inline if/else statements over if-else blocks
    "W605",    # don't report escape sequences in regular expressions
]

# Avoid trying to fix violations of these rules:
unfixable = [
    "B905",    # zip-without-explicit-strict
    "RET504",  # variable assignment before return
    "SIM108",  # simple if-else blocks
    "W605"     # escape sequences in regular expressions
]

# Use single quotes for strings:
flake8-quotes.inline-quotes = "single"

[format]
# Use single quotes for strings:
quote-style = "single"
