# Exclude the following directories:
exclude = [
    ".git",
    ".git-rewrite",
    ".ipynb_checkpoints",
    ".pyenv",
    ".ruff_cache",
    ".vscode",
    "__pycache__",
    "__pypackages__",
    "src/__pycache__",
    "src/pages/__pycache__",
    "data/R",
]

line-length = 90

# Automatically apply 'safe' fixes:
fix = true

# Enumerate all fixed violations:
show-fixes = true

# Assume Python >= 3.11
target-version = "py311"

[lint]
# Enable Pyflakes (`F`), a subset of the pycodestyle (`E`) codes,
# flake8-bugbear (`B`) rules, and isort (`I`) rules:
select = ["F", "E4", "E7", "E9", "B", "I"]

# Avoid trying to fix flake8-bugbear (`B`) violations:
unfixable = ["B"]

[format]
# Use single quotes for strings:
quote-style = "single"
